### ISSUE TITLE
What to display if a Deal is "verdealt"

### ISSUE THREAD

**Issue by indero** [mhutter/daydeal#11]
Currently it is not known what the output of the page is, as soon as the Deal is "verdealt". We might need to check for this case.

**Comment by indero** [comment]
The deal will just display 0%

```
    Riesiges Malset
    Crayola Painting Case

Für CHF CHF 14.90 anstatt statt CHF 25.90 (1)
Noch 0% verfügbar
```

**Comment by mhutter** [comment]
This is fine by me - WDYT?

**Comment by mhutter** [comment]
Goddamit, I could have used this painting set

**Comment by indero** [comment]
Can be closed. I was not sure if they use `0%` or if that would lead some strange output. Since it looks fine, this issue is not needed.
